### ISSUE TITLE
Failed to upgrade to `axum 0.7`

### ISSUE THREAD

**Issue by teenjuna** [robertwayne/axum-htmx#10]
Hey there! Today I tried to upgrade my app, which uses the latest version of this crate, to `axum 0.7`. As the title says, the attempt has failed. However, I still don't understand if cause of the problem sits inside the crate or in my code. Here is the code I'm talking about:
```rust
pub fn router() -> Router<Arc<ServerState>> {
    Router::new().route("/", get(page))
}

#[derive(Deserialize)]
struct PageQuery {
    category: Option<String>,
}

#[axum::debug_handler]
async fn page(
    State(state): State<Arc<ServerState>>,
    Query(query): Query<PageQuery>,
    HxTarget(target): HxTarget,
) -> Response {
    // ...
}
```

And here is the error:
```rust
error[E0277]: the trait bound `HxTarget: FromRequestParts<Arc<ServerState>>` is not satisfied
  --> src/server/pages/index.rs:33:23
   |
33 |     HxTarget(target): HxTarget,
   |                       ^^^^^^^^ the trait `FromRequestParts<Arc<ServerState>>` is not implemented for `HxTarget`
   |
   = help: the following other types implement trait `FromRequestParts<S>`:
             <tower_cookies::Cookies as FromRequestParts<S>>
             <tower_sessions::Session as FromRequestParts<S>>
             <UserId as FromRequestParts<ServerState>>
             <OptionalUserId as FromRequestParts<ServerState>>
             <HeaderMap as FromRequestParts<S>>
             <Extension<T> as FromRequestParts<S>>
             <axum::http::Method as FromRequestParts<S>>
             <axum::http::request::Parts as FromRequestParts<S>>
           and 32 others
   = note: required for `HxTarget` to implement `FromRequest<Arc<ServerState>, axum_core::extract::private::ViaParts>`
```

The first part says that `HxTarget` doesn't implement `FromRequestParts<Arc<ServerState>>`. However, it most certainly implements `FromRequestParts<S>`, and it worked before. `axum-htmx` depends on `axum-core 0.4`, same as `axum 0.7`. That's why I don't understand the error.

**Comment by teenjuna** [comment]
Okay, as David from axum [noticed](https://discord.com/channels/500028886025895936/870760546109116496/1180793770694942811) in Discord, the latest changes are just not published in `axum-htmx`.

Just a question, @robertwayne: is there any reason to wait for this?

**Comment by robertwayne** [comment]
I'll publish a release to crates.io today, after merging the PR ItsEzra has been working on. Sorry about the delay!

**Comment by robertwayne** [comment]
v0.5 is now available on crates.io and supports the latest axum version.
