### ISSUE TITLE
Adding HtmxResponse to easily set Htmx Response Headers

### ISSUE THREAD

**Issue by pfz4** [robertwayne/axum-htmx#4]
Hello,
would you mind if I create a PR implementing something like `HtmxResponse` in a builder-like pattern to easily set the response headers described in [https://htmx.org/docs/#response-headers](https://htmx.org/docs/#response-headers)?

**Comment by robertwayne** [comment]
I've thought about this a bit as well, so I'm definitely open to a PR.
